// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HillarysHairSalon.Migrations
{
    [DbContext(typeof(HillarysHairSalonDbContext))]
    [Migration("20240105152017_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HillarysHairSalon.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Scheduled")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StylistId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StylistId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 15,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 4,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 8,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 5,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 18,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 4,
                            IsCanceled = true,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 6,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 2,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 5,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 11,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 4,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 16,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 6,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 17,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 14,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 6,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 10,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 5,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 9,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 4,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 13,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 7,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 1,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 2, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 3,
                            IsCanceled = true,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 1,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 5,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 12,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 4,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 5,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 21,
                            CustomerId = 11,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 22,
                            CustomerId = 3,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 2, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 23,
                            CustomerId = 5,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 24,
                            CustomerId = 6,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 5,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 25,
                            CustomerId = 7,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 4,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 26,
                            CustomerId = 1,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 27,
                            CustomerId = 2,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 28,
                            CustomerId = 3,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 29,
                            CustomerId = 4,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 30,
                            CustomerId = 5,
                            IsCanceled = true,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 5,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 31,
                            CustomerId = 6,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 4,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 32,
                            CustomerId = 7,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 33,
                            CustomerId = 8,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 34,
                            CustomerId = 9,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 35,
                            CustomerId = 10,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 36,
                            CustomerId = 11,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 37,
                            CustomerId = 12,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 4,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 38,
                            CustomerId = 13,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 39,
                            CustomerId = 14,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 40,
                            CustomerId = 15,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 41,
                            CustomerId = 16,
                            IsCanceled = true,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 42,
                            CustomerId = 17,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 4, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 43,
                            CustomerId = 18,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 4,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 44,
                            CustomerId = 1,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 45,
                            CustomerId = 2,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 46,
                            CustomerId = 1,
                            IsCanceled = false,
                            IsComplete = true,
                            Scheduled = new DateTime(2024, 1, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 47,
                            CustomerId = 2,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 48,
                            CustomerId = 3,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 49,
                            CustomerId = 4,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 4,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 50,
                            CustomerId = 5,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 51,
                            CustomerId = 6,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 5, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 52,
                            CustomerId = 7,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 53,
                            CustomerId = 8,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 54,
                            CustomerId = 9,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 55,
                            CustomerId = 10,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 4,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 56,
                            CustomerId = 11,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 57,
                            CustomerId = 12,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 9, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 58,
                            CustomerId = 13,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 2,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 59,
                            CustomerId = 14,
                            IsCanceled = true,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 1,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 60,
                            CustomerId = 15,
                            IsCanceled = false,
                            IsComplete = false,
                            Scheduled = new DateTime(2024, 1, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StylistId = 3,
                            TotalCost = 0m
                        });
                });

            modelBuilder.Entity("HillarysHairSalon.Models.AppointmentService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppointmentServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 1,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 2,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 2,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 3,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 4,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 7,
                            AppointmentId = 4,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 5,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 9,
                            AppointmentId = 6,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 10,
                            AppointmentId = 7,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 11,
                            AppointmentId = 7,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 12,
                            AppointmentId = 8,
                            ServiceId = 10
                        },
                        new
                        {
                            Id = 13,
                            AppointmentId = 9,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 14,
                            AppointmentId = 9,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 15,
                            AppointmentId = 10,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 16,
                            AppointmentId = 11,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 17,
                            AppointmentId = 12,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 18,
                            AppointmentId = 13,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 19,
                            AppointmentId = 14,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 20,
                            AppointmentId = 14,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 21,
                            AppointmentId = 15,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 22,
                            AppointmentId = 15,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 23,
                            AppointmentId = 16,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 24,
                            AppointmentId = 16,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 25,
                            AppointmentId = 17,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 26,
                            AppointmentId = 17,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 27,
                            AppointmentId = 18,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 28,
                            AppointmentId = 18,
                            ServiceId = 10
                        },
                        new
                        {
                            Id = 29,
                            AppointmentId = 19,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 30,
                            AppointmentId = 19,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 31,
                            AppointmentId = 20,
                            ServiceId = 13
                        },
                        new
                        {
                            Id = 32,
                            AppointmentId = 20,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 33,
                            AppointmentId = 21,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 34,
                            AppointmentId = 21,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 35,
                            AppointmentId = 22,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 36,
                            AppointmentId = 22,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 37,
                            AppointmentId = 23,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 38,
                            AppointmentId = 23,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 39,
                            AppointmentId = 24,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 40,
                            AppointmentId = 24,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 41,
                            AppointmentId = 25,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 42,
                            AppointmentId = 25,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 43,
                            AppointmentId = 26,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 44,
                            AppointmentId = 27,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 45,
                            AppointmentId = 27,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 46,
                            AppointmentId = 28,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 47,
                            AppointmentId = 29,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 48,
                            AppointmentId = 30,
                            ServiceId = 10
                        },
                        new
                        {
                            Id = 49,
                            AppointmentId = 31,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 50,
                            AppointmentId = 32,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 51,
                            AppointmentId = 33,
                            ServiceId = 13
                        },
                        new
                        {
                            Id = 52,
                            AppointmentId = 33,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 53,
                            AppointmentId = 34,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 54,
                            AppointmentId = 35,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 55,
                            AppointmentId = 35,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 56,
                            AppointmentId = 36,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 57,
                            AppointmentId = 36,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 58,
                            AppointmentId = 37,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 59,
                            AppointmentId = 37,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 60,
                            AppointmentId = 38,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 61,
                            AppointmentId = 38,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 62,
                            AppointmentId = 38,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 63,
                            AppointmentId = 39,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 64,
                            AppointmentId = 40,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 65,
                            AppointmentId = 41,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 66,
                            AppointmentId = 41,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 67,
                            AppointmentId = 41,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 68,
                            AppointmentId = 42,
                            ServiceId = 15
                        },
                        new
                        {
                            Id = 69,
                            AppointmentId = 42,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 70,
                            AppointmentId = 42,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 71,
                            AppointmentId = 43,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 72,
                            AppointmentId = 43,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 73,
                            AppointmentId = 43,
                            ServiceId = 10
                        },
                        new
                        {
                            Id = 74,
                            AppointmentId = 44,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 75,
                            AppointmentId = 44,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 76,
                            AppointmentId = 45,
                            ServiceId = 14
                        },
                        new
                        {
                            Id = 77,
                            AppointmentId = 45,
                            ServiceId = 10
                        },
                        new
                        {
                            Id = 78,
                            AppointmentId = 45,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 79,
                            AppointmentId = 46,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 80,
                            AppointmentId = 46,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 81,
                            AppointmentId = 47,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 82,
                            AppointmentId = 48,
                            ServiceId = 14
                        },
                        new
                        {
                            Id = 83,
                            AppointmentId = 49,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 84,
                            AppointmentId = 50,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 85,
                            AppointmentId = 51,
                            ServiceId = 13
                        },
                        new
                        {
                            Id = 86,
                            AppointmentId = 51,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 87,
                            AppointmentId = 51,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 88,
                            AppointmentId = 52,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 89,
                            AppointmentId = 52,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 90,
                            AppointmentId = 52,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 91,
                            AppointmentId = 53,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 92,
                            AppointmentId = 54,
                            ServiceId = 10
                        },
                        new
                        {
                            Id = 93,
                            AppointmentId = 55,
                            ServiceId = 15
                        },
                        new
                        {
                            Id = 94,
                            AppointmentId = 56,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 95,
                            AppointmentId = 56,
                            ServiceId = 14
                        },
                        new
                        {
                            Id = 96,
                            AppointmentId = 56,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 97,
                            AppointmentId = 57,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 98,
                            AppointmentId = 58,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 99,
                            AppointmentId = 58,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 100,
                            AppointmentId = 59,
                            ServiceId = 13
                        },
                        new
                        {
                            Id = 101,
                            AppointmentId = 59,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 102,
                            AppointmentId = 60,
                            ServiceId = 5
                        });
                });

            modelBuilder.Entity("HillarysHairSalon.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = 1000000001
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = 1000000002
                        },
                        new
                        {
                            Id = 3,
                            Email = "emily.johnson@example.com",
                            FirstName = "Emily",
                            LastName = "Johnson",
                            PhoneNumber = 1000000003
                        },
                        new
                        {
                            Id = 4,
                            Email = "michael.williams@example.com",
                            FirstName = "Michael",
                            LastName = "Williams",
                            PhoneNumber = 1000000004
                        },
                        new
                        {
                            Id = 5,
                            Email = "david.brown@example.com",
                            FirstName = "David",
                            LastName = "Brown",
                            PhoneNumber = 1000000005
                        },
                        new
                        {
                            Id = 6,
                            Email = "sarah.davis@example.com",
                            FirstName = "Sarah",
                            LastName = "Davis",
                            PhoneNumber = 1000000006
                        },
                        new
                        {
                            Id = 7,
                            Email = "chris.miller@example.com",
                            FirstName = "Chris",
                            LastName = "Miller",
                            PhoneNumber = 1000000007
                        },
                        new
                        {
                            Id = 8,
                            Email = "anna.wilson@example.com",
                            FirstName = "Anna",
                            LastName = "Wilson",
                            PhoneNumber = 1000000008
                        },
                        new
                        {
                            Id = 9,
                            Email = "james.moore@example.com",
                            FirstName = "James",
                            LastName = "Moore",
                            PhoneNumber = 1000000009
                        },
                        new
                        {
                            Id = 10,
                            Email = "linda.taylor@example.com",
                            FirstName = "Linda",
                            LastName = "Taylor",
                            PhoneNumber = 1000000010
                        },
                        new
                        {
                            Id = 11,
                            Email = "robert.anderson@example.com",
                            FirstName = "Robert",
                            LastName = "Anderson",
                            PhoneNumber = 1000000011
                        },
                        new
                        {
                            Id = 12,
                            Email = "patricia.thomas@example.com",
                            FirstName = "Patricia",
                            LastName = "Thomas",
                            PhoneNumber = 1000000012
                        },
                        new
                        {
                            Id = 13,
                            Email = "mark.jackson@example.com",
                            FirstName = "Mark",
                            LastName = "Jackson",
                            PhoneNumber = 1000000013
                        },
                        new
                        {
                            Id = 14,
                            Email = "elizabeth.white@example.com",
                            FirstName = "Elizabeth",
                            LastName = "White",
                            PhoneNumber = 1000000014
                        },
                        new
                        {
                            Id = 15,
                            Email = "joseph.harris@example.com",
                            FirstName = "Joseph",
                            LastName = "Harris",
                            PhoneNumber = 1000000015
                        },
                        new
                        {
                            Id = 16,
                            Email = "susan.martin@example.com",
                            FirstName = "Susan",
                            LastName = "Martin",
                            PhoneNumber = 1000000016
                        },
                        new
                        {
                            Id = 17,
                            Email = "thomas.garcia@example.com",
                            FirstName = "Thomas",
                            LastName = "Garcia",
                            PhoneNumber = 1000000017
                        },
                        new
                        {
                            Id = 18,
                            Email = "jessica.rodriguez@example.com",
                            FirstName = "Jessica",
                            LastName = "Rodriguez",
                            PhoneNumber = 1000000018
                        });
                });

            modelBuilder.Entity("HillarysHairSalon.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 45.0m,
                            Name = "Women's Haircut"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 25.0m,
                            Name = "Men's Haircut"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 70.0m,
                            Name = "Hair Coloring"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 55.0m,
                            Name = "Partial Highlights"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 85.0m,
                            Name = "Full Highlights"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 20.0m,
                            Name = "Blow Dry"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 120.0m,
                            Name = "Keratin Treatment"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 30.0m,
                            Name = "Deep Conditioning Treatment"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 40.0m,
                            Name = "Simple Updo"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 60.0m,
                            Name = "Elaborate Updo"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 60.0m,
                            Name = "Perm"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 15.0m,
                            Name = "Beard Trim"
                        },
                        new
                        {
                            Id = 13,
                            Cost = 20.0m,
                            Name = "Men's Shave"
                        },
                        new
                        {
                            Id = 14,
                            Cost = 35.0m,
                            Name = "Men's Hair and Beard Package"
                        },
                        new
                        {
                            Id = 15,
                            Cost = 15.0m,
                            Name = "Eyebrow Shaping"
                        });
                });

            modelBuilder.Entity("HillarysHairSalon.Models.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Stylists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "hillary@example.com",
                            FirstName = "Hillary",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Johnson",
                            Password = "password1",
                            PhoneNumber = 1234567890,
                            StartDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Email = "james@example.com",
                            FirstName = "James",
                            IsActive = true,
                            IsAdmin = false,
                            LastName = "Smith",
                            Password = "password2",
                            PhoneNumber = 1234567891,
                            StartDate = new DateTime(2019, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Email = "emily@example.com",
                            FirstName = "Emily",
                            IsActive = true,
                            IsAdmin = false,
                            LastName = "Davis",
                            Password = "password3",
                            PhoneNumber = 1234567892,
                            StartDate = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Email = "michael@example.com",
                            FirstName = "Michael",
                            IsActive = true,
                            IsAdmin = false,
                            LastName = "Brown",
                            Password = "password4",
                            PhoneNumber = 1234567893,
                            StartDate = new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Email = "sophia@example.com",
                            EndDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophia",
                            IsActive = false,
                            IsAdmin = false,
                            LastName = "Miller",
                            Password = "password5",
                            PhoneNumber = 1234567894,
                            StartDate = new DateTime(2022, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Email = "lucas@example.com",
                            EndDate = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lucas",
                            IsActive = false,
                            IsAdmin = false,
                            LastName = "Wilson",
                            Password = "password6",
                            PhoneNumber = 1234567895,
                            StartDate = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HillarysHairSalon.Models.Appointment", b =>
                {
                    b.HasOne("HillarysHairSalon.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillarysHairSalon.Models.Stylist", "Stylist")
                        .WithMany("Appointments")
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("HillarysHairSalon.Models.AppointmentService", b =>
                {
                    b.HasOne("HillarysHairSalon.Models.Appointment", null)
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillarysHairSalon.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HillarysHairSalon.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("HillarysHairSalon.Models.Customer", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HillarysHairSalon.Models.Stylist", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
